name: send-news

on:
  schedule:
  # notify every 30min during trading hours, weekdays
    - cron: "5 23 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}


jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.8'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run Python
        run: python sending_stock_news.py
